name: tacentview
base: core24
# The version is parsed from Version.cmake.h using adopt-info. The version format is Major.Minor.Revision.
adopt-info: tacentview
summary: An immediate mode GUI image viewer.
description: |
  An image and texture viewer for tga, png, apng, exr, dds, pvr, ktx, ktx2, astc, pkm, qoi, gif, hdr,
  jpg, tif, ico, webp, and bmp files. Uses Dear ImGui and the Tacent library. Features correct handling
  of alpha channels, basic editing, colour quantization, flip-book generation, levels, raw data import,
  cropping, scaling/resizing, channel masking, cube/mip-map display, creation of animated images and a
  full-featured command-line interface for batch processing.
grade: stable       # Use either devel or stable.
confinement: strict # Use either devmode or strict.
platforms:
  amd64:
apps:
  tacentview:
    command: desktop-launch $SNAP/tacentview
    plugs:
    - x11
    - opengl
    - home
    - removable-media

parts:
  tacentview:
    stage-packages:
      - libgl1
      - libgl1-mesa-dri
      - libglu1-mesa
      - libx11-6
      # - libglx0
    plugin: cmake
    source: https://github.com/bluescan/tacentview.git
    # Handy for iterating src changes locally.
    # source: "tacentview_pullonly"
    # source-type: local
    cmake-parameters:
      - -G"Unix Makefiles"
      - -DCMAKE_BUILD_TYPE=Release
      - -DPACKAGE_SNAP=True
    build-packages:
      - make
      - cmake
      - libx11-dev
    override-pull: |
      echo OverridePullTacentView
      craftctl default
      VER=`grep -o '".*"' Src/Version.cmake.h | sed 's/"//g' | sed 's/[^.0-9]//g' # | sed 's/.*/\"&\"/g'`
      echo Parsed version string: $VER
      craftctl set version=$VER
    override-prime: |
      echo OverridePrimeTacentView
      craftctl default
      cp ../stage/root/parts/tacentview/build/ViewerInstall/tacentview tacentview
      mkdir -p Assets
      cp ../stage/root/parts/tacentview/build/ViewerInstall/Assets/* Assets/
    after:
      - desktop-glib-only

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
    override-prime: |
      echo OverridePrimeDesktop
      craftctl default
      cp ../stage/bin/desktop-launch desktop-launch
