# If you don't set these, they will be inferred from the repo's description on GitHub.
title: Tacent View
description: Homepage for Tacent View

show_downloads: true
theme: jekyll-theme-minimal
