# This workflow runs actions to pull and build tacit-texview
name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # The checkoutbuildwindows job builds tacentview on windows.
  checkoutbuildwindows:

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build CMake NMake.
    - uses: ilammy/msvc-dev-cmd@v1.2.0
    - name: Build using CMake MSVC
      run: |
        echo '*** CMake Configure ***'
        mkdir build
        cd build
        cmake .. -G"Visual Studio 16 2019" -Ax64
        echo '*** CMake Build ***'
        cmake --build . --config Release --target install
        echo '*** Done Building ***'
        
  # The checkoutbuildubuntu job builds tacentview on ubuntu.
  checkoutbuildubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Using Make
      run: |
        echo 'Build Using Make'
        #./Linux/fixup_makefiles_for_github_runner.sh
        #cd Linux
        #make All
        echo 'Done Build Using Make'
